### ISSUE TITLE
Theta with no used output is skipped after adding beq support

### ISSUE THREAD

**Issue by clyben** [egraphs-good/eggcc#164]
In PR[#161](https://github.com/oflatt/eggcc/pull/161), after adding beq support, the following program:
```
@main (arg : int) {
.start:
	cond : bool = const true;
	br cond .start .end;
.end:
	print arg; 
}
```
<img width="524" alt="image" src="https://github.com/oflatt/eggcc/assets/93016614/b29be1eb-a4ac-4165-baa2-ef2566cc07c7">
is optimized to print with no theta node.
<img width="217" alt="image" src="https://github.com/oflatt/eggcc/assets/93016614/cbaffde4-7de6-4d6b-8f71-e9d9ca7c77a2">

a similar program with computation in theta node not used outside:
```
@main (arg : int) {
	v : int = const 0;
.start:
	one : int = const 1;
	v : int = add one v;
	cond : bool = const true;
	br cond .start .end;
.end:
	print arg; 
}
```
is also ignored the loop in optimization.

**Comment by oflatt** [comment]
Closing because we are not working on the milestone
