### ISSUE TITLE
Crash in to_cfg

### ISSUE THREAD

**Issue by oflatt** [egraphs-good/eggcc#184]
```# ARGS: 10 10
@main(in1: int, in2: int) {
  four: int = const 4;
  a: bool = lt in1 four;
  br a .N .B;
  .N:
    br a .A .B;
  .A:
    y: int = const 6;
    jmp .end;
  .B:
    y: int = const 7;
    jmp .end;
  .end:
    print y;
}```

**Comment by ezrosent** [comment]
With my new branch we can translate the CFG correctly:

![cfg-structured](https://github.com/egraphs-good/eggcc/assets/3622899/7813c7c2-fcf8-4e85-a916-398b157b5be8)


But we get further issues. the logic still works but now we don't have that all uses of `y` are dominated by definitions (there's an unreachable path in the new structured CFG that doesn't define y before printing it).

**Comment by ezrosent** [comment]
Still, this is progress. We can potentially just synthesize a fake value here if we can detect the issue.

**Comment by oflatt** [comment]
Great!
Alternatively, we can ban cfgs where the value is not defined in all branches

**Comment by oflatt** [comment]
One easy way to do this is run Bril's SSA conversion and detect if there are any "undefined" values

**Comment by oflatt** [comment]
Oh, I understand now. The input is valid but the one you generated isn't.

**Comment by ezrosent** [comment]
@oflatt Take a look at the above commit, particularly the changes to `from_cfg.rs`: it works for simple types, but I think filling in those todos would be pretty difficult. other ideas:

* Add special functions that don't take state edges but return pointers / states?
* Alternative would be add a special 'undefined' type to the IR, but then I think that could recreate the same problem when translating back.

**Comment by oflatt** [comment]
A few questions:
- Can your algorithm detect which blocks are unreachable? These are the problematic ones right?
- Is it possible that the state edge isn't bound? It seems like it should always be bound. Otherwise, to make up pointers we can always insert an allocation right?
- Another idea: For unreachable blocks, is it possible to keep track of what the variable is bound to in the other path, and do whatever it does? For example, in the CFG above as far as I can tell the problem is `y` isn't bound in node 9. If we added the same code as node 4 it would solve the problem.

**Comment by ezrosent** [comment]
> Can your algorithm detect which blocks are unreachable? These are the problematic ones right?

Would that help? We need them regardless I think.

> Is it possible that the state edge isn't bound?

I don't think so. Good point!

> Otherwise, to make up pointers we can always insert an allocation right?

Only if there is already a state edge argument to the current block I think. Otherwise you need to go back and add state edges everywhere (nasty, would prefer to avoid).

> Another idea: For unreachable blocks, is it possible to keep track of what the variable is bound to in the other path, and do whatever it does? For example, in the CFG above as far as I can tell the problem is y isn't bound in node 9. If we added the same code as node 4 it would solve the problem.

I tried this, just for pointers, and the generated RVSDG looks okay but the generated bril is invalid! For reference this goes from:

```
@main() {
  one: int = const 1;
  three: int = const 3;
  four: int = const 4;
  six: int = const 6;
  seven: int = const 7;

  in1: ptr<int> = alloc one;
  in2: ptr<int> = alloc one;
  store in1 six;
  store in2 seven;
  a: bool = lt three four;
  br a .N .B;
.N:
  br a .A .B;
.A:
  y: ptr<int> = id in1;
  jmp .end;
.B:
  y: ptr<int> = id in2;
  jmp .end;
.end:
  x: int = load y;
  free in1;
  free in2;
  print x;
}
```

to 

```
@main {
  v1: int = const 3;
  v3: int = const 4;
  v5: bool = lt v1 v3;
  v8: int = const 1;
  v12: ptr<int> = alloc v8;
  v14: ptr<int> = alloc v8;
  v16: int = const 7;
  v19: int = const 6;
  store v12 v19;
  store v14 v16;
  v26: bool = const false;
  br v5 .__63__ .__29__;
.__63__:
  v68: bool = const false;
  br v5 .__80__ .__70__;
.__80__:
  v75: ptr<int> = id v14;
  v76: ptr<int> = id v12;
  v77: ptr<int> = id v12;
  v78: bool = id v53;
.__86__:
  v58: ptr<int> = id v75;
  v59: ptr<int> = id v76;
  v60: ptr<int> = id v77;
  v61: bool = id v78;
.__92__:
  br v61 .__106__ .__98__;
.__106__:
  v102: ptr<int> = id v58;
  v103: ptr<int> = id v59;
  v104: ptr<int> = id v60;
  jmp .__111__;
.__98__:
  v102: ptr<int> = id v58;
  v103: ptr<int> = id v59;
  v104: ptr<int> = id v58;
  jmp .__111__;
.__70__:
  v75: ptr<int> = id v14;
  v76: ptr<int> = id v12;
  v77: ptr<int> = id v12;
  v78: bool = id v37;
  jmp .__86__;
.__29__:
  v37: bool = const false;
  br v5 .__49__ .__39__;
.__49__:
  v53: bool = const true;
  v44: ptr<int> = id v14;
  v45: ptr<int> = id v12;
  v46: ptr<int> = id v12;
  v47: bool = id v53;
.__56__:
  v58: ptr<int> = id v14;
  v59: ptr<int> = id v12;
  v60: ptr<int> = id v46;
  v61: bool = id v26;
  jmp .__92__;
.__39__:
  v44: ptr<int> = id v14;
  v45: ptr<int> = id v12;
  v46: ptr<int> = id v12;
  v47: bool = id v37;
  jmp .__56__;
.__111__:
  v113: int = load v104;
  free v103;
  free v102;
  print v113;
}
```

Hard to read, but `v57` isn't bound when we run block `.__80__`.

**Comment by ezrosent** [comment]
I think next steps are:

* Submit this improved code, without the extra handling for pointers (none of our existing test cases exercise it right now).
* Continue debugging to see if this is a problem with RVSDG => bril. If so, maybe I'll move onto that. If not, continue working through the translation code.

**Comment by oflatt** [comment]
Thank you for answering my questions!

Don't we add state edges everywhere anyways?
For example, we need to add them to pure loops because they might not terminate.

**Comment by oflatt** [comment]
Oh I anticipate problems with freeing the memory at that pointer- Bril throws an error if there is a memory leak

**Comment by oflatt** [comment]
Your next steps sound good to me
