### ISSUE TITLE
[Tree Optimizer] Add a function environment to the interpreter

### ISSUE THREAD

**Issue by Alex-Fischman** [egraphs-good/eggcc#261]
Right now the interpreter and typechecker panic/do a bad job when run on functions and function calls. We should fix this.

**Comment by oflatt** [comment]
I think that the interpreter should run on new thing called a `Program` which is a list of functions. The first function will be the "main" function
That way I can translate Bril to a `Program`

**Comment by oflatt** [comment]
Fixed in new schema
