### ISSUE TITLE
Rvsdg conversion bug with unstructured program

### ISSUE THREAD

**Issue by oflatt** [egraphs-good/eggcc#307]
Found a bug in converting an unstructured program to RVSDG.
Repro: https://github.com/egraphs-good/eggcc/tree/oflatt-rvsdg-bug-repro

**Comment by ezrosent** [comment]
@oflatt any chance you have this one around somewhere? This link is broken now.

**Comment by oflatt** [comment]
Whoops, lost this one. Closing this
