### ISSUE TITLE
Add `brilift` integration to compile Bril to LLVM

### ISSUE THREAD

**Issue by Alex-Fischman** [egraphs-good/eggcc#385]
https://capra.cs.cornell.edu/bril/tools/brilift.html

https://github.com/sampsyo/bril/tree/main/brilift

**Comment by Pat-Lafon** [comment]
Hello, I was interested when I saw this issue. Is there a specific reason to be using brilift as opposed to brillvm for translating bril to llvm? Sorry, there might not be enough context for me to understand.

**Comment by oflatt** [comment]
We plan to use both!

**Comment by Pat-Lafon** [comment]
Ah, very cool. Good Luck!

**Comment by Alex-Fischman** [comment]
Closed by #408.
